// Generated by tools/check_lean_refs.py: Lean declarations, their files, and line numbers.
window.LEANINDEX = {
 "Bridge": [
  "PIFoundation.lean",
  1742
 ],
 "Cantor": [
  "PIFoundation.lean",
  1727
 ],
 "Cong": [
  "PIFoundation.lean",
  1698
 ],
 "Derive.d_Cantor": [
  "PIDerivations.lean",
  733
 ],
 "Derive.d_Cong_of_Recovery": [
  "PIDerivations.lean",
  1005
 ],
 "Derive.d_Disjoint_of_LLPoly": [
  "PIDerivations.lean",
  655
 ],
 "Derive.d_ExtT_of_Disjoint": [
  "PIDerivations.lean",
  1087
 ],
 "Derive.d_Hae_Cong": [
  "PIDerivations.lean",
  856
 ],
 "Derive.d_IntT_of_ExtT": [
  "PIDerivations.lean",
  1124
 ],
 "Derive.d_LLEqv_of_Cong_Truth": [
  "PIDerivations.lean",
  624
 ],
 "Derive.d_Link": [
  "PIDerivations.lean",
  496
 ],
 "Derive.d_PCong": [
  "PIDerivations.lean",
  599
 ],
 "Derive.d_Recovery": [
  "PIDerivations.lean",
  610
 ],
 "Derive.d_Recovery_of_Cong": [
  "PIDerivations.lean",
  1043
 ],
 "Derive.d_Slogan_Hae": [
  "PIDerivations.lean",
  830
 ],
 "Derive.d_SymTeq": [
  "PIDerivations.lean",
  475
 ],
 "Derive.d_TopBot": [
  "PIDerivations.lean",
  589
 ],
 "Derive.d_TransTeq": [
  "PIDerivations.lean",
  486
 ],
 "Derive.d_Truth": [
  "PIDerivations.lean",
  579
 ],
 "Derive.d_Twin": [
  "PIDerivations.lean",
  789
 ],
 "Derive.d_Twin_Disjoint": [
  "PIDerivations.lean",
  805
 ],
 "Derive.d_WCong": [
  "PIDerivations.lean",
  959
 ],
 "Disjoint": [
  "PIFoundation.lean",
  1686
 ],
 "ExtT": [
  "PIFoundation.lean",
  1735
 ],
 "Frame.PropExt_valid": [
  "PINew.lean",
  47
 ],
 "Hae": [
  "PIFoundation.lean",
  1695
 ],
 "Inj": [
  "PIFoundation.lean",
  1718
 ],
 "IntT": [
  "PIFoundation.lean",
  1739
 ],
 "LLEqv": [
  "PIFoundation.lean",
  946
 ],
 "LLPoly": [
  "PIFoundation.lean",
  964
 ],
 "Link": [
  "PIFoundation.lean",
  1683
 ],
 "M0_Cong": [
  "PIFoundation.lean",
  2075
 ],
 "M0_Disjoint": [
  "PIFoundation.lean",
  2072
 ],
 "M0_ExtT": [
  "PIFoundation.lean",
  2078
 ],
 "M0_Inj": [
  "PIFoundation.lean",
  2076
 ],
 "M0_IntT": [
  "PIFoundation.lean",
  2880
 ],
 "M0_LLEqv": [
  "PIFoundation.lean",
  2071
 ],
 "M0_LLPoly": [
  "PIFoundation.lean",
  2073
 ],
 "M0_PExt": [
  "PINew.lean",
  190
 ],
 "M0_Slogan": [
  "PIFoundation.lean",
  2080
 ],
 "M0_model": [
  "PIFoundation.lean",
  2070
 ],
 "M0_not_Twin": [
  "PIFoundation.lean",
  2079
 ],
 "M0e_Cong": [
  "PIFoundation.lean",
  2113
 ],
 "M0e_Disjoint": [
  "PIFoundation.lean",
  2110
 ],
 "M0e_ExtT": [
  "PIFoundation.lean",
  2116
 ],
 "M0e_Inj": [
  "PIFoundation.lean",
  2114
 ],
 "M0e_IntT": [
  "PIFoundation.lean",
  2881
 ],
 "M0e_LLEqv": [
  "PIFoundation.lean",
  2109
 ],
 "M0e_LLPoly": [
  "PIFoundation.lean",
  2111
 ],
 "M0e_PExt": [
  "PINew.lean",
  191
 ],
 "M0e_model": [
  "PIFoundation.lean",
  2108
 ],
 "M0e_not_Slogan": [
  "PIFoundation.lean",
  2118
 ],
 "M0e_not_Twin": [
  "PIFoundation.lean",
  2117
 ],
 "M1_ExtT": [
  "PIFoundation.lean",
  2313
 ],
 "M1_Inj": [
  "PIFoundation.lean",
  2301
 ],
 "M1_IntT": [
  "PIFoundation.lean",
  2886
 ],
 "M1_LLEqv": [
  "PIFoundation.lean",
  2300
 ],
 "M1_Slogan": [
  "PIFoundation.lean",
  2712
 ],
 "M1_model": [
  "PIFoundation.lean",
  2299
 ],
 "M1_not_Disjoint": [
  "PIFoundation.lean",
  2302
 ],
 "M1_not_LLPoly": [
  "PIFoundation.lean",
  2305
 ],
 "MD_Cantor": [
  "PIExplore.lean",
  119
 ],
 "MD_Disjoint": [
  "PIFoundation.lean",
  2397
 ],
 "MD_ExtT": [
  "PIExplore.lean",
  123
 ],
 "MD_Inj": [
  "PIFoundation.lean",
  2398
 ],
 "MD_IntT": [
  "PIExplore.lean",
  126
 ],
 "MD_Slogan": [
  "PIExplore.lean",
  120
 ],
 "MD_TopBot": [
  "PIExplore.lean",
  125
 ],
 "MD_Truth": [
  "PIExplore.lean",
  124
 ],
 "MD_model": [
  "PIFoundation.lean",
  2396
 ],
 "MD_not_Bridge": [
  "PIFoundation.lean",
  2417
 ],
 "MD_not_Hae": [
  "PIExplore.lean",
  121
 ],
 "MD_not_LLEqv": [
  "PIFoundation.lean",
  2399
 ],
 "MD_not_LLPoly": [
  "PIFoundation.lean",
  2414
 ],
 "MD_not_PCong": [
  "PIExplore.lean",
  127
 ],
 "MD_not_PExt": [
  "PINew.lean",
  210
 ],
 "MD_not_Twin": [
  "PIExplore.lean",
  122
 ],
 "MD_not_WCong": [
  "PIExplore.lean",
  131
 ],
 "MDtw_Cantor": [
  "PIExplore.lean",
  513
 ],
 "MDtw_Inj": [
  "PIExplore.lean",
  486
 ],
 "MDtw_Slogan": [
  "PIExplore.lean",
  515
 ],
 "MDtw_TopBot": [
  "PIExplore.lean",
  499
 ],
 "MDtw_Truth": [
  "PIExplore.lean",
  497
 ],
 "MDtw_Twin": [
  "PIExplore.lean",
  494
 ],
 "MDtw_model": [
  "PIExplore.lean",
  485
 ],
 "MDtw_not_Bridge": [
  "PIExplore.lean",
  544
 ],
 "MDtw_not_Disjoint": [
  "PIExplore.lean",
  505
 ],
 "MDtw_not_ExtT": [
  "PIExplore.lean",
  508
 ],
 "MDtw_not_Hae": [
  "PIExplore.lean",
  517
 ],
 "MDtw_not_IntT": [
  "PIExplore.lean",
  512
 ],
 "MDtw_not_LLEqv": [
  "PIExplore.lean",
  502
 ],
 "MDtw_not_PCong": [
  "PIExplore.lean",
  520
 ],
 "MDtw_not_WCong": [
  "PIExplore.lean",
  524
 ],
 "ME_Cantor": [
  "PIExplore.lean",
  136
 ],
 "ME_Disjoint": [
  "PIFoundation.lean",
  2429
 ],
 "ME_ExtT": [
  "PIExplore.lean",
  140
 ],
 "ME_Inj": [
  "PIFoundation.lean",
  2430
 ],
 "ME_IntT": [
  "PIExplore.lean",
  143
 ],
 "ME_PCong": [
  "PIFoundation.lean",
  2434
 ],
 "ME_Slogan": [
  "PIExplore.lean",
  137
 ],
 "ME_TopBot": [
  "PIExplore.lean",
  142
 ],
 "ME_Truth": [
  "PIExplore.lean",
  141
 ],
 "ME_model": [
  "PIFoundation.lean",
  2428
 ],
 "ME_not_Hae": [
  "PIExplore.lean",
  138
 ],
 "ME_not_LLEqv": [
  "PIFoundation.lean",
  2431
 ],
 "ME_not_Twin": [
  "PIExplore.lean",
  139
 ],
 "ME_not_WCong": [
  "PIFoundation.lean",
  2442
 ],
 "MEk_Disjoint": [
  "PIBridge.lean",
  225
 ],
 "MEk_Inj": [
  "PIBridge.lean",
  53
 ],
 "MEk_PCong": [
  "PIBridge.lean",
  61
 ],
 "MEk_model": [
  "PIBridge.lean",
  52
 ],
 "MEk_not_Bridge": [
  "PIBridge.lean",
  100
 ],
 "Mall_Bridge": [
  "PIExplore.lean",
  202
 ],
 "Mall_Cong": [
  "PIExplore.lean",
  175
 ],
 "Mall_Hae": [
  "PIExplore.lean",
  178
 ],
 "Mall_Inj": [
  "PIExplore.lean",
  174
 ],
 "Mall_PCong": [
  "PIExplore.lean",
  177
 ],
 "Mall_PExt": [
  "PINew.lean",
  246
 ],
 "Mall_Twin": [
  "PIExplore.lean",
  179
 ],
 "Mall_WCong": [
  "PIExplore.lean",
  176
 ],
 "Mall_model": [
  "PIExplore.lean",
  173
 ],
 "Mall_not_Cantor": [
  "PIExplore.lean",
  186
 ],
 "Mall_not_Disjoint": [
  "PIExplore.lean",
  189
 ],
 "Mall_not_ExtT": [
  "PIExplore.lean",
  193
 ],
 "Mall_not_IntT": [
  "PIExplore.lean",
  196
 ],
 "Mall_not_LLEqv": [
  "PIExplore.lean",
  181
 ],
 "Mall_not_LLPoly": [
  "PIExplore.lean",
  199
 ],
 "Mall_not_Slogan": [
  "PIExplore.lean",
  191
 ],
 "Mall_not_TopBot": [
  "PIExplore.lean",
  185
 ],
 "Mall_not_Truth": [
  "PIExplore.lean",
  183
 ],
 "Mbt_Cong": [
  "PINew.lean",
  303
 ],
 "Mbt_ExtT": [
  "PINew.lean",
  337
 ],
 "Mbt_Inj": [
  "PINew.lean",
  287
 ],
 "Mbt_IntT": [
  "PINew.lean",
  352
 ],
 "Mbt_LLEqv": [
  "PINew.lean",
  302
 ],
 "Mbt_Slogan": [
  "PINew.lean",
  322
 ],
 "Mbt_model": [
  "PINew.lean",
  286
 ],
 "Mbt_not_PExt": [
  "PINew.lean",
  315
 ],
 "Mcan_Inj": [
  "PIExplore.lean",
  227
 ],
 "Mcan_TopBot": [
  "PIExplore.lean",
  238
 ],
 "Mcan_Truth": [
  "PIExplore.lean",
  236
 ],
 "Mcan_model": [
  "PIExplore.lean",
  226
 ],
 "Mcan_not_Cantor": [
  "PIExplore.lean",
  241
 ],
 "Mcan_not_Disjoint": [
  "PIExplore.lean",
  247
 ],
 "Mcan_not_ExtT": [
  "PIExplore.lean",
  272
 ],
 "Mcan_not_Hae": [
  "PIExplore.lean",
  266
 ],
 "Mcan_not_IntT": [
  "PIExplore.lean",
  276
 ],
 "Mcan_not_LLEqv": [
  "PIExplore.lean",
  244
 ],
 "Mcan_not_LLPoly": [
  "PIExplore.lean",
  277
 ],
 "Mcan_not_PCong": [
  "PIExplore.lean",
  252
 ],
 "Mcan_not_Slogan": [
  "PIExplore.lean",
  250
 ],
 "Mcan_not_Twin": [
  "PIExplore.lean",
  260
 ],
 "Mcan_not_WCong": [
  "PIExplore.lean",
  256
 ],
 "Mcard_Cong": [
  "PIFoundation.lean",
  2215
 ],
 "Mcard_Disjoint": [
  "PIFoundation.lean",
  2709
 ],
 "Mcard_ExtT": [
  "PIFoundation.lean",
  2710
 ],
 "Mcard_IntT": [
  "PIFoundation.lean",
  2883
 ],
 "Mcard_LLEqv": [
  "PIFoundation.lean",
  2212
 ],
 "Mcard_LLPoly": [
  "PIFoundation.lean",
  2213
 ],
 "Mcard_PExt": [
  "PINew.lean",
  193
 ],
 "Mcard_Recovery": [
  "PIFoundation.lean",
  2216
 ],
 "Mcard_model": [
  "PIFoundation.lean",
  2211
 ],
 "Mcard_not_Inj": [
  "PIFoundation.lean",
  2218
 ],
 "Mct_ExtT": [
  "PIExplore.lean",
  366
 ],
 "Mct_Inj": [
  "PIExplore.lean",
  332
 ],
 "Mct_IntT": [
  "PIExplore.lean",
  381
 ],
 "Mct_Slogan": [
  "PIExplore.lean",
  353
 ],
 "Mct_TopBot": [
  "PIExplore.lean",
  347
 ],
 "Mct_Truth": [
  "PIExplore.lean",
  345
 ],
 "Mct_model": [
  "PIExplore.lean",
  331
 ],
 "Mct_not_Cantor": [
  "PIExplore.lean",
  350
 ],
 "Mct_not_Disjoint": [
  "PIExplore.lean",
  385
 ],
 "Mct_not_Hae": [
  "PIExplore.lean",
  393
 ],
 "Mct_not_LLEqv": [
  "PIExplore.lean",
  382
 ],
 "Mct_not_PCong": [
  "PIExplore.lean",
  398
 ],
 "Mct_not_Twin": [
  "PIExplore.lean",
  388
 ],
 "Mct_not_WCong": [
  "PIExplore.lean",
  402
 ],
 "Mfn_Cantor": [
  "PIExplore.lean",
  150
 ],
 "Mfn_ExtT": [
  "PIExplore.lean",
  154
 ],
 "Mfn_Inj": [
  "PIFoundation.lean",
  2485
 ],
 "Mfn_IntT": [
  "PIExplore.lean",
  157
 ],
 "Mfn_LLPoly": [
  "PIFoundation.lean",
  2496
 ],
 "Mfn_PExt": [
  "PINew.lean",
  249
 ],
 "Mfn_Slogan": [
  "PIExplore.lean",
  151
 ],
 "Mfn_TopBot": [
  "PIExplore.lean",
  156
 ],
 "Mfn_Truth": [
  "PIExplore.lean",
  155
 ],
 "Mfn_model": [
  "PIFoundation.lean",
  2484
 ],
 "Mfn_not_Hae": [
  "PIExplore.lean",
  152
 ],
 "Mfn_not_LLEqv": [
  "PIFoundation.lean",
  2486
 ],
 "Mfn_not_PCong": [
  "PIExplore.lean",
  158
 ],
 "Mfn_not_Twin": [
  "PIExplore.lean",
  153
 ],
 "Mfn_not_WCong": [
  "PIFoundation.lean",
  2489
 ],
 "Mh_ExtT": [
  "PIFoundation.lean",
  2653
 ],
 "Mh_Hae": [
  "PIFoundation.lean",
  2608
 ],
 "Mh_Inj": [
  "PIFoundation.lean",
  2606
 ],
 "Mh_IntT": [
  "PIFoundation.lean",
  2887
 ],
 "Mh_LLEqv": [
  "PIFoundation.lean",
  2605
 ],
 "Mh_PCong": [
  "PIFoundation.lean",
  2622
 ],
 "Mh_Twin": [
  "PIFoundation.lean",
  2616
 ],
 "Mh_model": [
  "PIFoundation.lean",
  2604
 ],
 "Mh_not_Cong": [
  "PIFoundation.lean",
  2644
 ],
 "Mhb_Hae": [
  "PIBridge.lean",
  132
 ],
 "Mhb_Inj": [
  "PIBridge.lean",
  134
 ],
 "Mhb_Twin": [
  "PIBridge.lean",
  133
 ],
 "Mhb_model": [
  "PIBridge.lean",
  131
 ],
 "Mhb_not_Bridge": [
  "PIBridge.lean",
  218
 ],
 "Mhk_Hae": [
  "PIHae.lean",
  590
 ],
 "Mhk_LLEqv": [
  "PIHae.lean",
  588
 ],
 "Mhk_Twin": [
  "PIHae.lean",
  592
 ],
 "Mhk_model": [
  "PIHae.lean",
  582
 ],
 "Mhk_not_Inj": [
  "PIHae.lean",
  595
 ],
 "Mhk_not_Recovery": [
  "PIHae.lean",
  598
 ],
 "Mhm_Hae": [
  "PIHae.lean",
  267
 ],
 "Mhm_Inj": [
  "PIHae.lean",
  269
 ],
 "Mhm_Twin": [
  "PIHae.lean",
  268
 ],
 "Mhm_model": [
  "PIHae.lean",
  266
 ],
 "Mhm_not_LLEqv": [
  "PIHae.lean",
  291
 ],
 "Mhm_not_PCong": [
  "PIHae.lean",
  294
 ],
 "Mhm_not_WCong": [
  "PIHae.lean",
  300
 ],
 "Mhp_Hae": [
  "PIHae.lean",
  193
 ],
 "Mhp_Inj": [
  "PIHae.lean",
  195
 ],
 "Mhp_LLEqv": [
  "PIHae.lean",
  192
 ],
 "Mhp_Twin": [
  "PIHae.lean",
  194
 ],
 "Mhp_model": [
  "PIHae.lean",
  191
 ],
 "Mhp_not_ExtT": [
  "PIHae.lean",
  237
 ],
 "Mhp_not_IntT": [
  "PIHae.lean",
  250
 ],
 "Mhp_not_PCong": [
  "PIHae.lean",
  229
 ],
 "Mhp_not_PExt": [
  "PINew.lean",
  254
 ],
 "Mk_Disjoint": [
  "PIFoundation.lean",
  2704
 ],
 "Mk_ExtT": [
  "PIFoundation.lean",
  2705
 ],
 "Mk_IntT": [
  "PIFoundation.lean",
  2882
 ],
 "Mk_LLEqv": [
  "PIFoundation.lean",
  2153
 ],
 "Mk_LLPoly": [
  "PIFoundation.lean",
  2154
 ],
 "Mk_PExt": [
  "PINew.lean",
  192
 ],
 "Mk_Slogan": [
  "PIFoundation.lean",
  2706
 ],
 "Mk_model": [
  "PIFoundation.lean",
  2152
 ],
 "Mk_not_Cong": [
  "PIFoundation.lean",
  2160
 ],
 "Mk_not_Inj": [
  "PIFoundation.lean",
  2156
 ],
 "Mk_not_PCong": [
  "PIFoundation.lean",
  2700
 ],
 "Mp_Inj": [
  "PIFoundation.lean",
  2347
 ],
 "Mp_LLEqv": [
  "PIFoundation.lean",
  2346
 ],
 "Mp_Slogan": [
  "PIFoundation.lean",
  2719
 ],
 "Mp_model": [
  "PIFoundation.lean",
  2345
 ],
 "Mp_not_Disjoint": [
  "PIFoundation.lean",
  2348
 ],
 "Mp_not_PCong": [
  "PIFoundation.lean",
  2352
 ],
 "Mp_not_PExt": [
  "PINew.lean",
  201
 ],
 "Mr_Cong": [
  "PIFoundation.lean",
  2251
 ],
 "Mr_LLEqv": [
  "PIFoundation.lean",
  2250
 ],
 "Mr_PExt": [
  "PINew.lean",
  194
 ],
 "Mr_model": [
  "PIFoundation.lean",
  2249
 ],
 "Mr_not_Disjoint": [
  "PIFoundation.lean",
  2252
 ],
 "Mr_not_ExtT": [
  "PIFoundation.lean",
  2696
 ],
 "Mr_not_IntT": [
  "PIFoundation.lean",
  2884
 ],
 "Mr_not_LLPoly": [
  "PIFoundation.lean",
  2255
 ],
 "Mrec_Cong": [
  "PIFoundation.lean",
  2846
 ],
 "Mrec_LLEqv": [
  "PIFoundation.lean",
  2845
 ],
 "Mrec_PExt": [
  "PINew.lean",
  196
 ],
 "Mrec_Slogan": [
  "PIFoundation.lean",
  2855
 ],
 "Mrec_model": [
  "PIFoundation.lean",
  2844
 ],
 "Mrec_not_Disjoint": [
  "PIFoundation.lean",
  2856
 ],
 "Mrec_not_Inj": [
  "PIFoundation.lean",
  2851
 ],
 "Mrec_not_Recovery": [
  "PIFoundation.lean",
  2847
 ],
 "Mt2_LLEqv": [
  "PIFoundation.lean",
  3016
 ],
 "Mt2_PExt": [
  "PINew.lean",
  197
 ],
 "Mt2_Twin": [
  "PIFoundation.lean",
  3017
 ],
 "Mt2_model": [
  "PIFoundation.lean",
  3015
 ],
 "Mt2_not_Disjoint": [
  "PIFoundation.lean",
  3033
 ],
 "Mt2_not_Inj": [
  "PIFoundation.lean",
  3025
 ],
 "Mt2_not_PCong": [
  "PIFoundation.lean",
  3021
 ],
 "Mt2_not_Recovery": [
  "PIFoundation.lean",
  3029
 ],
 "Mtot_Cantor": [
  "PIExplore.lean",
  145
 ],
 "Mtot_Cong": [
  "PIFoundation.lean",
  2463
 ],
 "Mtot_ExtT": [
  "PIFoundation.lean",
  2466
 ],
 "Mtot_Inj": [
  "PIFoundation.lean",
  2456
 ],
 "Mtot_LLPoly": [
  "PIFoundation.lean",
  2469
 ],
 "Mtot_PExt": [
  "PINew.lean",
  247
 ],
 "Mtot_Slogan": [
  "PIExplore.lean",
  146
 ],
 "Mtot_model": [
  "PIFoundation.lean",
  2455
 ],
 "Mtot_not_Hae": [
  "PIExplore.lean",
  147
 ],
 "Mtot_not_IntT": [
  "PIFoundation.lean",
  2890
 ],
 "Mtot_not_LLEqv": [
  "PIFoundation.lean",
  2457
 ],
 "Mtot_not_TopBot": [
  "PIFoundation.lean",
  2461
 ],
 "Mtot_not_Truth": [
  "PIFoundation.lean",
  2459
 ],
 "Mtot_not_Twin": [
  "PIExplore.lean",
  148
 ],
 "Mtw_Cong": [
  "PIFoundation.lean",
  2788
 ],
 "Mtw_Inj": [
  "PIFoundation.lean",
  2789
 ],
 "Mtw_LLEqv": [
  "PIFoundation.lean",
  2787
 ],
 "Mtw_PExt": [
  "PINew.lean",
  195
 ],
 "Mtw_Slogan": [
  "PIFoundation.lean",
  2795
 ],
 "Mtw_Twin": [
  "PIFoundation.lean",
  2791
 ],
 "Mtw_model": [
  "PIFoundation.lean",
  2786
 ],
 "Mtw_not_Disjoint": [
  "PIFoundation.lean",
  2796
 ],
 "Mtw_not_ExtT": [
  "PIFoundation.lean",
  2798
 ],
 "Mtw_not_Hae": [
  "PIFoundation.lean",
  2801
 ],
 "Mtw_not_IntT": [
  "PIFoundation.lean",
  2885
 ],
 "PCong": [
  "PIFoundation.lean",
  1713
 ],
 "PExt": [
  "PINew.lean",
  34
 ],
 "PropExt": [
  "PINew.lean",
  16
 ],
 "Recovery": [
  "PIFoundation.lean",
  1721
 ],
 "Slogan": [
  "PIFoundation.lean",
  1689
 ],
 "SymTeq": [
  "PIFoundation.lean",
  1678
 ],
 "Tg.Mi_Cong": [
  "PINew.lean",
  420
 ],
 "Tg.Mi_Inj": [
  "PINew.lean",
  418
 ],
 "Tg.Mi_IntT": [
  "PITagged.lean",
  680
 ],
 "Tg.Mi_LLEqv": [
  "PITagged.lean",
  657
 ],
 "Tg.Mi_PExt": [
  "PINew.lean",
  423
 ],
 "Tg.Mi_Slogan": [
  "PINew.lean",
  417
 ],
 "Tg.Mi_Twin": [
  "PINew.lean",
  415
 ],
 "Tg.Mi_model": [
  "PITagged.lean",
  636
 ],
 "Tg.Mi_not_ExtT": [
  "PITagged.lean",
  666
 ],
 "Tg.Mi_not_PropExt": [
  "PINew.lean",
  220
 ],
 "Tg.Mit_IntT": [
  "PITagged.lean",
  815
 ],
 "Tg.Mit_model": [
  "PITagged.lean",
  794
 ],
 "Tg.Mit_not_PropExt": [
  "PINew.lean",
  231
 ],
 "Tg.Mit_not_TopBot": [
  "PITagged.lean",
  797
 ],
 "Tg.Mit_not_Truth": [
  "PITagged.lean",
  800
 ],
 "Tg.Mtb_TopBot": [
  "PITagged.lean",
  766
 ],
 "Tg.Mtb_model": [
  "PITagged.lean",
  763
 ],
 "Tg.Mtb_not_PropExt": [
  "PINew.lean",
  225
 ],
 "Tg.Mtb_not_Truth": [
  "PITagged.lean",
  774
 ],
 "Tg.Mz_Cong": [
  "PINew.lean",
  464
 ],
 "Tg.Mz_Disjoint": [
  "PINew.lean",
  448
 ],
 "Tg.Mz_ExtT": [
  "PINew.lean",
  449
 ],
 "Tg.Mz_IntT": [
  "PINew.lean",
  451
 ],
 "Tg.Mz_LLEqv": [
  "PINew.lean",
  439
 ],
 "Tg.Mz_PExt": [
  "PINew.lean",
  468
 ],
 "Tg.Mz_Slogan": [
  "PINew.lean",
  463
 ],
 "Tg.Mz_model": [
  "PINew.lean",
  435
 ],
 "Tg.Mz_not_PropExt": [
  "PINew.lean",
  459
 ],
 "TopBot": [
  "PIFoundation.lean",
  1730
 ],
 "TransTeq": [
  "PIFoundation.lean",
  1680
 ],
 "Truth": [
  "PIFoundation.lean",
  1724
 ],
 "Twin": [
  "PIFoundation.lean",
  1692
 ],
 "WCong": [
  "PIFoundation.lean",
  1705
 ],
 "d_Bridge": [
  "PISchemas.lean",
  195
 ],
 "d_Bridge_of_LLPoly": [
  "PISchemas.lean",
  226
 ],
 "d_ExtT_of_PropExt": [
  "PINew.lean",
  156
 ],
 "d_LLPoly_of_Disjoint": [
  "PISchemas.lean",
  208
 ],
 "d_TopBot_of_Truth": [
  "PIExplore.lean",
  290
 ],
 "d_Truth_of_PropExt": [
  "PINew.lean",
  124
 ],
 "d_WCong_of_Cong": [
  "PIExplore.lean",
  300
 ]
};
