// Generated by tools/check_lean_refs.py: Lean declarations, their files, and line numbers.
window.LEANINDEX = {
 "Bridge": [
  "PIFoundation.lean",
  1742
 ],
 "Cantor": [
  "PIFoundation.lean",
  1727
 ],
 "Cong": [
  "PIFoundation.lean",
  1698
 ],
 "Derive.d_Cantor": [
  "PIDerivations.lean",
  733
 ],
 "Derive.d_Cong_of_Recovery": [
  "PIDerivations.lean",
  1005
 ],
 "Derive.d_Disjoint_of_LLPoly": [
  "PIDerivations.lean",
  655
 ],
 "Derive.d_ExtT_of_Disjoint": [
  "PIDerivations.lean",
  1087
 ],
 "Derive.d_Hae_Cong": [
  "PIDerivations.lean",
  856
 ],
 "Derive.d_IntT_of_ExtT": [
  "PIDerivations.lean",
  1124
 ],
 "Derive.d_LLEqv_of_Cong_Truth": [
  "PIDerivations.lean",
  624
 ],
 "Derive.d_Link": [
  "PIDerivations.lean",
  496
 ],
 "Derive.d_PCong": [
  "PIDerivations.lean",
  599
 ],
 "Derive.d_Recovery": [
  "PIDerivations.lean",
  610
 ],
 "Derive.d_Recovery_of_Cong": [
  "PIDerivations.lean",
  1043
 ],
 "Derive.d_Slogan_Hae": [
  "PIDerivations.lean",
  830
 ],
 "Derive.d_SymTeq": [
  "PIDerivations.lean",
  475
 ],
 "Derive.d_TopBot": [
  "PIDerivations.lean",
  589
 ],
 "Derive.d_TransTeq": [
  "PIDerivations.lean",
  486
 ],
 "Derive.d_Truth": [
  "PIDerivations.lean",
  579
 ],
 "Derive.d_Twin": [
  "PIDerivations.lean",
  789
 ],
 "Derive.d_Twin_Disjoint": [
  "PIDerivations.lean",
  805
 ],
 "Derive.d_WCong": [
  "PIDerivations.lean",
  959
 ],
 "Disjoint": [
  "PIFoundation.lean",
  1686
 ],
 "ExtT": [
  "PIFoundation.lean",
  1735
 ],
 "Hae": [
  "PIFoundation.lean",
  1695
 ],
 "Inj": [
  "PIFoundation.lean",
  1718
 ],
 "IntT": [
  "PIFoundation.lean",
  1739
 ],
 "LLEqv": [
  "PIFoundation.lean",
  946
 ],
 "LLPoly": [
  "PIFoundation.lean",
  964
 ],
 "Link": [
  "PIFoundation.lean",
  1683
 ],
 "M0_Cong": [
  "PIFoundation.lean",
  2075
 ],
 "M0_Disjoint": [
  "PIFoundation.lean",
  2072
 ],
 "M0_ExtT": [
  "PIFoundation.lean",
  2078
 ],
 "M0_Inj": [
  "PIFoundation.lean",
  2076
 ],
 "M0_IntT": [
  "PIFoundation.lean",
  2880
 ],
 "M0_LLEqv": [
  "PIFoundation.lean",
  2071
 ],
 "M0_LLPoly": [
  "PIFoundation.lean",
  2073
 ],
 "M0_Slogan": [
  "PIFoundation.lean",
  2080
 ],
 "M0_model": [
  "PIFoundation.lean",
  2070
 ],
 "M0_not_Twin": [
  "PIFoundation.lean",
  2079
 ],
 "M0e_Cong": [
  "PIFoundation.lean",
  2113
 ],
 "M0e_Disjoint": [
  "PIFoundation.lean",
  2110
 ],
 "M0e_ExtT": [
  "PIFoundation.lean",
  2116
 ],
 "M0e_Inj": [
  "PIFoundation.lean",
  2114
 ],
 "M0e_IntT": [
  "PIFoundation.lean",
  2881
 ],
 "M0e_LLEqv": [
  "PIFoundation.lean",
  2109
 ],
 "M0e_LLPoly": [
  "PIFoundation.lean",
  2111
 ],
 "M0e_model": [
  "PIFoundation.lean",
  2108
 ],
 "M0e_not_Slogan": [
  "PIFoundation.lean",
  2118
 ],
 "M0e_not_Twin": [
  "PIFoundation.lean",
  2117
 ],
 "M1_ExtT": [
  "PIFoundation.lean",
  2313
 ],
 "M1_Inj": [
  "PIFoundation.lean",
  2301
 ],
 "M1_IntT": [
  "PIFoundation.lean",
  2886
 ],
 "M1_LLEqv": [
  "PIFoundation.lean",
  2300
 ],
 "M1_Slogan": [
  "PIFoundation.lean",
  2712
 ],
 "M1_model": [
  "PIFoundation.lean",
  2299
 ],
 "M1_not_Disjoint": [
  "PIFoundation.lean",
  2302
 ],
 "M1_not_LLPoly": [
  "PIFoundation.lean",
  2305
 ],
 "MD_Disjoint": [
  "PIFoundation.lean",
  2397
 ],
 "MD_Inj": [
  "PIFoundation.lean",
  2398
 ],
 "MD_model": [
  "PIFoundation.lean",
  2396
 ],
 "MD_not_Bridge": [
  "PIFoundation.lean",
  2417
 ],
 "MD_not_LLEqv": [
  "PIFoundation.lean",
  2399
 ],
 "MD_not_LLPoly": [
  "PIFoundation.lean",
  2414
 ],
 "ME_Disjoint": [
  "PIFoundation.lean",
  2429
 ],
 "ME_Inj": [
  "PIFoundation.lean",
  2430
 ],
 "ME_PCong": [
  "PIFoundation.lean",
  2434
 ],
 "ME_model": [
  "PIFoundation.lean",
  2428
 ],
 "ME_not_LLEqv": [
  "PIFoundation.lean",
  2431
 ],
 "ME_not_WCong": [
  "PIFoundation.lean",
  2442
 ],
 "Mcard_Cong": [
  "PIFoundation.lean",
  2215
 ],
 "Mcard_Disjoint": [
  "PIFoundation.lean",
  2709
 ],
 "Mcard_ExtT": [
  "PIFoundation.lean",
  2710
 ],
 "Mcard_IntT": [
  "PIFoundation.lean",
  2883
 ],
 "Mcard_LLEqv": [
  "PIFoundation.lean",
  2212
 ],
 "Mcard_LLPoly": [
  "PIFoundation.lean",
  2213
 ],
 "Mcard_Recovery": [
  "PIFoundation.lean",
  2216
 ],
 "Mcard_model": [
  "PIFoundation.lean",
  2211
 ],
 "Mcard_not_Inj": [
  "PIFoundation.lean",
  2218
 ],
 "Mfn_Inj": [
  "PIFoundation.lean",
  2485
 ],
 "Mfn_LLPoly": [
  "PIFoundation.lean",
  2496
 ],
 "Mfn_model": [
  "PIFoundation.lean",
  2484
 ],
 "Mfn_not_LLEqv": [
  "PIFoundation.lean",
  2486
 ],
 "Mfn_not_WCong": [
  "PIFoundation.lean",
  2489
 ],
 "Mh_ExtT": [
  "PIFoundation.lean",
  2653
 ],
 "Mh_Hae": [
  "PIFoundation.lean",
  2608
 ],
 "Mh_Inj": [
  "PIFoundation.lean",
  2606
 ],
 "Mh_IntT": [
  "PIFoundation.lean",
  2887
 ],
 "Mh_LLEqv": [
  "PIFoundation.lean",
  2605
 ],
 "Mh_PCong": [
  "PIFoundation.lean",
  2622
 ],
 "Mh_Twin": [
  "PIFoundation.lean",
  2616
 ],
 "Mh_model": [
  "PIFoundation.lean",
  2604
 ],
 "Mh_not_Cong": [
  "PIFoundation.lean",
  2644
 ],
 "Mk_Disjoint": [
  "PIFoundation.lean",
  2704
 ],
 "Mk_ExtT": [
  "PIFoundation.lean",
  2705
 ],
 "Mk_IntT": [
  "PIFoundation.lean",
  2882
 ],
 "Mk_LLEqv": [
  "PIFoundation.lean",
  2153
 ],
 "Mk_LLPoly": [
  "PIFoundation.lean",
  2154
 ],
 "Mk_Slogan": [
  "PIFoundation.lean",
  2706
 ],
 "Mk_model": [
  "PIFoundation.lean",
  2152
 ],
 "Mk_not_Cong": [
  "PIFoundation.lean",
  2160
 ],
 "Mk_not_Inj": [
  "PIFoundation.lean",
  2156
 ],
 "Mk_not_PCong": [
  "PIFoundation.lean",
  2700
 ],
 "Mp_Inj": [
  "PIFoundation.lean",
  2347
 ],
 "Mp_LLEqv": [
  "PIFoundation.lean",
  2346
 ],
 "Mp_Slogan": [
  "PIFoundation.lean",
  2719
 ],
 "Mp_model": [
  "PIFoundation.lean",
  2345
 ],
 "Mp_not_Disjoint": [
  "PIFoundation.lean",
  2348
 ],
 "Mp_not_PCong": [
  "PIFoundation.lean",
  2352
 ],
 "Mr_Cong": [
  "PIFoundation.lean",
  2251
 ],
 "Mr_LLEqv": [
  "PIFoundation.lean",
  2250
 ],
 "Mr_model": [
  "PIFoundation.lean",
  2249
 ],
 "Mr_not_Disjoint": [
  "PIFoundation.lean",
  2252
 ],
 "Mr_not_ExtT": [
  "PIFoundation.lean",
  2696
 ],
 "Mr_not_IntT": [
  "PIFoundation.lean",
  2884
 ],
 "Mr_not_LLPoly": [
  "PIFoundation.lean",
  2255
 ],
 "Mrec_Cong": [
  "PIFoundation.lean",
  2846
 ],
 "Mrec_LLEqv": [
  "PIFoundation.lean",
  2845
 ],
 "Mrec_Slogan": [
  "PIFoundation.lean",
  2855
 ],
 "Mrec_model": [
  "PIFoundation.lean",
  2844
 ],
 "Mrec_not_Disjoint": [
  "PIFoundation.lean",
  2856
 ],
 "Mrec_not_Inj": [
  "PIFoundation.lean",
  2851
 ],
 "Mrec_not_Recovery": [
  "PIFoundation.lean",
  2847
 ],
 "Mt2_LLEqv": [
  "PIFoundation.lean",
  3016
 ],
 "Mt2_Twin": [
  "PIFoundation.lean",
  3017
 ],
 "Mt2_model": [
  "PIFoundation.lean",
  3015
 ],
 "Mt2_not_Disjoint": [
  "PIFoundation.lean",
  3033
 ],
 "Mt2_not_Inj": [
  "PIFoundation.lean",
  3025
 ],
 "Mt2_not_PCong": [
  "PIFoundation.lean",
  3021
 ],
 "Mt2_not_Recovery": [
  "PIFoundation.lean",
  3029
 ],
 "Mtot_Cong": [
  "PIFoundation.lean",
  2463
 ],
 "Mtot_ExtT": [
  "PIFoundation.lean",
  2466
 ],
 "Mtot_Inj": [
  "PIFoundation.lean",
  2456
 ],
 "Mtot_LLPoly": [
  "PIFoundation.lean",
  2469
 ],
 "Mtot_model": [
  "PIFoundation.lean",
  2455
 ],
 "Mtot_not_IntT": [
  "PIFoundation.lean",
  2890
 ],
 "Mtot_not_LLEqv": [
  "PIFoundation.lean",
  2457
 ],
 "Mtot_not_TopBot": [
  "PIFoundation.lean",
  2461
 ],
 "Mtot_not_Truth": [
  "PIFoundation.lean",
  2459
 ],
 "Mtw_Cong": [
  "PIFoundation.lean",
  2788
 ],
 "Mtw_Inj": [
  "PIFoundation.lean",
  2789
 ],
 "Mtw_LLEqv": [
  "PIFoundation.lean",
  2787
 ],
 "Mtw_Slogan": [
  "PIFoundation.lean",
  2795
 ],
 "Mtw_Twin": [
  "PIFoundation.lean",
  2791
 ],
 "Mtw_model": [
  "PIFoundation.lean",
  2786
 ],
 "Mtw_not_Disjoint": [
  "PIFoundation.lean",
  2796
 ],
 "Mtw_not_ExtT": [
  "PIFoundation.lean",
  2798
 ],
 "Mtw_not_Hae": [
  "PIFoundation.lean",
  2801
 ],
 "Mtw_not_IntT": [
  "PIFoundation.lean",
  2885
 ],
 "PCong": [
  "PIFoundation.lean",
  1713
 ],
 "Recovery": [
  "PIFoundation.lean",
  1721
 ],
 "Slogan": [
  "PIFoundation.lean",
  1689
 ],
 "SymTeq": [
  "PIFoundation.lean",
  1678
 ],
 "TopBot": [
  "PIFoundation.lean",
  1730
 ],
 "TransTeq": [
  "PIFoundation.lean",
  1680
 ],
 "Truth": [
  "PIFoundation.lean",
  1724
 ],
 "Twin": [
  "PIFoundation.lean",
  1692
 ],
 "WCong": [
  "PIFoundation.lean",
  1705
 ],
 "d_Bridge": [
  "PISchemas.lean",
  195
 ],
 "d_LLPoly_of_Disjoint": [
  "PISchemas.lean",
  208
 ]
};
