"""Check that every Lean name referenced in data.js is a declaration in the Lean files, and write
lean-index.js, mapping each name to its file and line (for links from the site).

Usage: python3 tools/check_lean_refs.py                      (writes lean-index.js)
       python3 tools/check_lean_refs.py --check              (fails if lean-index.js is out of date)
       python3 tools/check_lean_refs.py --leanfile OUT       (also writes a Lean file of #check lines)
"""
import json, re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
data = (root / "data.js").read_text()
files = ["PIFoundation.lean", "PIDerivations.lean", "PISchemas.lean", "PIExplore.lean", "PIHae.lean", "PITagged.lean", "PIBridge.lean", "PINew.lean", "PINF.lean", "PIModal.lean", "PIWorlds.lean", "PIAlg.lean", "PIAlgModels.lean", "PIAlgI.lean", "PIAlgIModels.lean", "PIBarcan.lean", "PIBarcanModels.lean", "PIClass.lean", "PIClassModels.lean", "PIKripke.lean", "PIKripkeModels.lean", "PIKripkeND.lean", "PIKripkeHae.lean", "PIKripkeCong.lean", "PINoSelf.lean", "PICongQs.lean", "PIHaeQs.lean", "PIModalX.lean", "PIModalX2.lean", "PIBF.lean", "PIOQ_KBF.lean", "PIOQ_Mr2.lean", "PIOQ_Mco.lean", "PIOQ_Der.lean", "PIOQ_Mcl.lean", "PIOQ_Mtt.lean", "PIOQ_MttT.lean", "PIOQ_MId.lean", "PIOQ_Small.lean", "PIOQ_Tow2.lean", "PIOQ_KIE.lean", "PIOQ_LLP.lean", "PIOQ_Swap.lean", "PIOQ_MIdB.lean", "PIOQ_DerBF.lean", "PIOQ_F3c.lean"]

names = set(re.findall(r'lean: "([A-Za-z0-9_.]+)"', data))
for block in re.findall(r'lean: \{([^}]*)\}', data):
    names.update(re.findall(r'"([A-Za-z0-9_.]+)"', block))

decl = {}
for f in files:
    for i, line in enumerate((root / "lean" / f).read_text().splitlines(), 1):
        m = re.match(r'\s*(?:noncomputable )?(?:theorem|def|abbrev|structure)\s+([A-Za-z0-9_.]+)', line)
        if m:
            decl.setdefault(m.group(1), (f, i))

def lookup(n):
    return decl.get(n.split(".")[-1])

missing = sorted(n for n in names if lookup(n) is None)
if missing:
    print("Lean names in data.js with no declaration:", ", ".join(missing))
    sys.exit(1)

index = {n: list(lookup(n)) for n in sorted(names)}
out = "// Generated by tools/check_lean_refs.py: Lean declarations, their files, and line numbers.\nwindow.LEANINDEX = " + json.dumps(index, indent=1) + ";\n"
target = root / "lean-index.js"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != out:
        print("lean-index.js is out of date; run python3 tools/check_lean_refs.py")
        sys.exit(1)
else:
    target.write_text(out)
if "--leanfile" in sys.argv:
    path = sys.argv[sys.argv.index("--leanfile") + 1]
    body = "import PIFoundation\nimport PIDerivations\nimport PISchemas\nimport PIExplore\nimport PIHae\nimport PITagged\nimport PIBridge\nimport PINew\nimport PINF\nimport PIModal\nimport PIWorlds\nimport PIAlg\nimport PIAlgModels\nimport PIAlgI\nimport PIAlgIModels\nimport PIBarcan\nimport PIBarcanModels\nimport PIClass\nimport PIClassModels\nimport PIKripke\nimport PIKripkeModels\nimport PIKripkeND\nimport PIKripkeHae\nimport PIKripkeCong\nimport PINoSelf\nimport PICongQs\nimport PIHaeQs\nimport PIModalX\nimport PIModalX2\nimport PIBF\nimport PIOQ_KBF\nimport PIOQ_Mr2\nimport PIOQ_Mco\nimport PIOQ_Der\nimport PIOQ_Mcl\nimport PIOQ_Mtt\nimport PIOQ_MttT\nimport PIOQ_MId\nimport PIOQ_Small\nimport PIOQ_Tow2\nimport PIOQ_KIE\nimport PIOQ_LLP\nimport PIOQ_Swap\nimport PIOQ_MIdB\nimport PIOQ_DerBF\nimport PIOQ_F3c\n" + "\n".join(f"#check @PIF.{n}" for n in sorted(names)) + "\n"
    pathlib.Path(path).write_text(body)
print(f"{len(names)} Lean names checked.")
